# Generated by Django 5.0.6 on 2024-07-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_like_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
