# Generated by Django 5.0.6 on 2024-07-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
