# Generated by Django 5.0.6 on 2024-07-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
