# Generated by Django 5.0.6 on 2024-07-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_like_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_count',
        ),
    ]
