# Generated by Django 5.0.6 on 2024-07-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_by', to='network.post'),
        ),
    ]
