# Generated by Django 5.0.6 on 2024-07-12 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_user_liked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
