# Generated by Django 5.0.6 on 2024-07-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_post_liked_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked_posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_posts',
        ),
    ]
