# Generated by Django 5.0.6 on 2024-07-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
