# Generated by Django 5.0.6 on 2024-07-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_like_liked_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
