# Generated by Django 5.0.6 on 2024-07-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_remove_like_liked_count_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
