# Generated by Django 5.0.6 on 2024-07-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
